[[pages]]
path = "example_one.py"
name = "st-pages"
icon = "ğŸ“„"

[[pages]]
path = "example_two.py"
name = "Example Two"
icon = "â³"

[[pages]]
path = "example_four.py"
name = "Try hiding pages"
icon = "ğŸ“–"

[[pages]]
path = "example_three.py"

icon = "ğŸ“„"

[[pages]]
path = "example_five.py"
name = "Example Five"
icon = "ğŸ§°"
url_path = "a_very_long_page_title"
